import exceptions


class MiException(exceptions.ArithmeticError):
    pass


class MiExceptionWrong(exceptions.foo):
    pass
